routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::resource('invoice', 'invoiceController');
Route::get('/','invoiceController@index')->name('index');
Route::get('/pdf/{id}', 'DynamicPDFController@pdf')->name('pdf');
Route::get('/excel/{id}','ExcelController@export_excel')->name('export_excel');

resources/views/editInvoice.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Invoice</title>

        <!-- link -->
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/all.css') }}">
        <!--script-->
        <script src="{{ URL::asset('js/jquery.js') }}"></script>
        <script src="{{ URL::asset('js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ URL::asset('js/newInvoice.js') }}"></script>

        <!-- Styles -->
        <style>
        </style>
    </head>
    <body>
    <div class="container" id="main_wrapper">
        @if(session('info'))
            <div class="alert alert-success alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a> 
                    {{session('info')}}
            </div>
        @endif
        <form action="{{route('invoice.update',$invoice->id)}}" method="post">
            @csrf
             {{method_field('PATCH')}}
            <div class="form-row mt-1">
                <div class="form-group col-md" style="display:flex;align-items:center;">
                    <label for="itemName" class="mr-2 btn-info btn"
                    onclick="location.reload()">
                        <i class="fas fa-edit"></i>Edit Invoice&nbsp;
                    </label>
                     <label for="itemName" class="mr-2 btn-primary btn" 
                     onclick="window.location.href='{{route('index')}}'">
                        <i class="fas fa-eye"></i>View Invoices&nbsp;
                    </label>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md" style="display:flex;align-items:center;">
                    <label for="itemName" class="mr-2 col-form-label">
                        Invoice Name&nbsp;
                    </label>
                    <input type="text" value="{{$invoice->name}}" class="form-control form-control-sm col-sm-3" autocomplete="off" name="invoiceName"  placeholder="Invoice Name" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md mr-5">
                    <label for="itemName" class="mr-2 col-form-label-sm">
                        Item Name&nbsp;
                    </label>
                </div>
                <div class="form-group col-md mr-5">
                    <label for="noOfItem" class="mr-2 col-form-label-sm">
                        # of Items&nbsp;
                    </label>
                </div>
                <div class="form-group col-md mr-5">
                    <label for="Price" class="mr-2 col-form-label-sm">
                        Price&nbsp;
                    </label>
                </div>
                <div class="form-group col-md mr-5">
                    <label for="" class="mr-2 col-form-label-sm">
                        Total&nbsp;
                    </label>
                </div>
                <div class="form-group col-md mr-5">
                    
                </div>
            </div>
            @foreach($invoice->items as $item)
            <div class="form-row cloneMe" id="cloneMe">
                <div class="form-group col-md mr-5">
                    <input type="text" value="{{$item->name}}" class="form-control form-control-sm" autocomplete="off" name="itemName[]"  placeholder="Item Name" required>
                </div>
                <div class="form-group col-md mr-5">
                    <input type="number" value="{{$item->noOfItem}}" class="form-control form-control-sm noOfItem" autocomplete="off" name="noOfItems[]"  placeholder="# of Items" required
                    min=0>
                </div>
                <div class="form-group col-md mr-5">
                    <input type="number" value="{{$item->price}}" class="form-control form-control-sm price" autocomplete="off" name="price[]" placeholder="Price" required 
                    step=0.01 min=0>
                </div>
                <div class="form-group col-md mr-5">
                    <input type="number" value="{{$item->total}}" class="form-control form-control-sm total" autocomplete="off" name="total[]" placeholder="Total" required readonly 
                    style="background:white;" step=0.01>
                </div>
                <div class="form-group col-md mr-5">
                    <button class="btn btn-danger pr-1 pl-1 pt-0 pb-0" title="Remove"
                    onclick="sub(this)" type="button">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </div>
            </div>
            @endforeach
            <div class="form-row" id="cloneAbove">
                <div class="form-group col-lg-12">
                   <button type="button" class="btn btn-primary btn-sm" id="addItem">
                        <i class="fas fa-plus"></i>Add Item(<spam id="countItem"></spam>)
                   </button>
                </div>
            </div>
            <div class="form-row mt-1">
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md text-right">
                     <label for="itemName" class="mr-2 col-form-label-sm">
                        Sub Total&nbsp;
                    </label>
                </div>
                <div class="form-group col-md">
                    <input type="number" value="{{$invoice->sub_total}}" 
                    class="form-control form-control-sm"  
                    name="subTotal" id="subTotal" required readonly 
                    style="background:white;" step=0.01> 
                </div>
                <div class="form-group col-md">
                    
                </div>
            </div>
             <div class="form-row mt">
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md text-right">
                     <label for="itemName" class="mr-2 col-form-label-sm">
                        Tax&nbsp;
                    </label>
                </div>
                <div class="form-group col-md">
                    <input type="number" value="{{$invoice->tax}}" 
                    class="form-control form-control-sm"  
                    name="tax" id="tax" required min=0 step=0.01> 
                </div>
                <div class="form-group col-md">
                    
                </div>
            </div>
            <div class="form-row mt">
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md text-right">
                     <label for="itemName" class="mr-2 col-form-label-sm">
                        Grand Total&nbsp;
                    </label>
                </div>
                <div class="form-group col-md">
                    <input type="number" value="{{$invoice->grand_total}}" 
                    class="form-control form-control-sm"  
                    name="gTotal" id="gTotal" required readonly style="background:white;"
                    step=0.01> 
                </div>
                <div class="form-group col-md">
                    
                </div>
            </div>
             <div class="form-row" id="cloneAbove">
                <div class="form-group col-lg-12">
                   <button class="btn btn-info btn-sm" type="submit">
                      <i class="fas fa-arrow-circle-up"></i>Update
                   </button>
                    <button class="btn btn-light btn-sm" type="reset">
                      <i class="fas fa-redo-alt"></i>Reset
                   </button>
                </div>
            </div>
        </form>
    </div>
    </body>
</html>

resources/views/index.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Invoice</title>

        <!-- link -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/jquery.dataTables.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/datatable.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/jquery.dataTables_themeroller.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/all.css') }}">
        <!--script-->
        <script src="{{ URL::asset('js/jquery.js') }}"></script>
        <script src="{{ URL::asset('js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ URL::asset('js/newInvoice.js') }}"></script>
       <!--  <script src="{{ URL::asset('js/jquery.dataTables.js') }}"></script>
        <script src="{{ URL::asset('js/jquery.dataTables.min.js') }}"></script> -->
        <script src="{{ URL::asset('js/index.js') }}"></script>
        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                margin: 0;
            }

            .f-style{
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 100;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .code {
                border-right:2px solid;
                font-size: 26px;
                padding: 0 15px 0 15px;
                text-align: center;
            }

            .message {
                font-size: 18px;
                text-align: center;
            }
            .t-underline{
                text-decoration:underline;
            }
            .dataTables_wrapper .dataTables_filter{
                float:left;
                text-align:left;
                margin-bottom:15px;
            }
            .dataTables_length{
                float:right;
                margin-top:15px;
                margin-bottom:-15px;
            }
            .dataTables_info {
                clear: both;
                float: left;
                padding-top: 0.55em;
            }
        </style>
    </head>
    <body>
    <div class="container" id="main_wrapper">
        @if(session('info'))
            <div class="alert alert-success alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a> 
                    {{session('info')}}
            </div>
        @endif
        @if(isset($invoice))
            @if(sizeof($invoice)>0)
        <div id="show_table_length" class="dataTables_length">
            <a href="{{route('invoice.create')}}" class="btn btn-primary"> 
                <i class="fas fa-plus"></i>Add Invoice
            </a>
        </div>
        <div id="show_table_info" class="dataTables_info">
            <label>
                Total Invoice : {{$invoice->total()}}
            </label>
        </div>
        <div>
            <table id="show_table" class="table table-striped" 
            style="white-space:nowrap;table-layout:fixed;">
                <thead class="thead-dark">
                    <tr>
                        <th>Invoice Name</th>
                        <th>#of Items</th>
                        <th>Total</th>
                        <th style="width:7%"></th>
                        <th style="width:7%"></th>
                        <th style="width:7%"></th>
                        <th style="width:10%"></th>
                    </tr>
                </thead>
                <tbody>
                  @foreach($invoice as $i)
                    <tr>
                        <td style="vertical-align:middle;">
                          <a href="{{url('/invoice',$i->id)}}" class="t-underline" 
                            target="_blank">
                              {{$i->name}}
                          </a>
                        </td>
                        <td style="vertical-align:middle;">{{sizeof($i->items)}}</td>
                        <td style="vertical-align:middle;">{{$i->grand_total}}</td>
                        <td class="border" style="text-align:center;vertical-align:middle;">
                            <!-- <a  href="{{url('/pdf',$i->id)}}"
                                class="t-underline text-success" 
                                target="_blank"> -->
                            <a class="t-underline text-success" 
                               href="{{url('/pdf',$i->id)}}"
                               onclick="window.open(this.href, 'newwindow', 'width=850, height=950'); 
                               return false;">
                                    PDF
                            </a>
                        </td>
                         <td class="border" style="text-align:center;vertical-align:middle;">
                            <a  href="{{url('/excel',$i->id)}}"
                                class="t-underline text-success">
                                    Excel
                            </a>
                        </td>
                        <td class="border" style="text-align:center;vertical-align:middle;">
                             <a href="{{route('invoice.edit',$i->id)}}" class="t-underline">
                                    Edit
                            </a>
                        </td>
                        <td class="border" style="vertical-align:middle;">
                            <form method="post" action="{{route('invoice.destroy',$i->id)}}" onsubmit="return confirm('Are you sure to delete \'{{$i->name}}\' invoice?');">
                                @csrf
                                {{method_field('delete')}}
                                <button class="t-underline text-danger btn btn-link">
                                    Remove
                                </button>
                            </form>
                        </td>
                    </tr>
                  @endforeach
                </tbody>
            </table>
            
        </div>
        <div style="text-align:center" class="mt-5">
            <div style="display:inline-block;">
                {{ $invoice->links() }}
            </div>
        </div>
            @endif
        @endif
        @if(isset($invoice))
            @if(sizeof($invoice)==0)
        <div class="flex-center position-ref full-height f-style">
            <div class="code">
                No Invoice Found ?
            </div>
            <div class="message" style="padding:10px">
                <a href="{{route('invoice.create')}}" class="btn btn-primary"> 
                    <i class="fas fa-plus"></i>Add First Invoice
                </a>          
            </div>
        </div>
            @endif
        @endif
    </div>
    </body>
</html>

resources/views/invoice.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Invoice</title>

        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/all.css') }}">
        <!--script-->
        <script src="{{ URL::asset('js/jquery.js') }}"></script>
        <script src="{{ URL::asset('js/bootstrap.bundle.min.js') }}"></script>

        <!-- Styles -->
        <style>
        </style>
    </head>
    <body>
    <div class="container" id="main_wrapper">
        @if(session('info'))
            <div class="alert alert-success alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a> 
                    {{session('info')}}
            </div>
        @endif
        <h3 align="center">
            <span class="text-primary">Invoice Name : </span>
            <span class="text-warning">{{$invoice_data->name}}</span>
        </h3>
        <table width="100%" class="mt-5" style="border-collapse: collapse; border: 0px;">
            <tr>
                <th style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%">Item Name</th>
                <th style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%"># of Items</th>
                <th style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%">Price</th>
                <th style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%">Total</th>
            </tr>
            @foreach($invoice_data->items as $item)
            <tr>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;">{{$item->name}}
                </td>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;">{{$item->noOfItem}}
                </td>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;">{{$item->price}}
                </td>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;">{{$item->total}}
                </td>
            </tr>
            @endforeach
        </table>
        <table width="100%" class="mt-5 mb-5" style="border-collapse:collapse;border:0px;">
            <tr>
                <td></td>
                <td></td>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%">Sub Total</td>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%">
                {{$invoice_data->sub_total}}</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%">Tax</td>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%">
                {{$invoice_data->tax}}</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%">Grand Total</td>
                <td style="border: 1px solid; padding:12px;text-align:center;vertical-align:middle;" width="25%">
                {{$invoice_data->grand_total}}</td>
            </tr>
        </table>
    </div>
    </body>
</html>

resources/views/newInvoice.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Invoice</title>

        <!-- link -->
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/all.css') }}">
        <!--script-->
        <script src="{{ URL::asset('js/jquery.js') }}"></script>
        <script src="{{ URL::asset('js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ URL::asset('js/newInvoice.js') }}"></script>

        <!-- Styles -->
        <style>
        </style>
    </head>
    <body>
    <div class="container" id="main_wrapper">
        @if(session('info'))
            <div class="alert alert-success alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a> 
                    {{session('info')}}
            </div>
        @endif
        <form action="{{route('invoice.store')}}" method="post">
            @csrf
            <div class="form-row mt-1">
                <div class="form-group col-md" style="display:flex;align-items:center;">
                    <label for="itemName" class="mr-2 btn-info btn"
                    onclick="location.reload()">
                        <i class="fas fa-file-invoice"></i>New Invoice&nbsp;
                    </label>
                     <label for="itemName" class="mr-2 btn-primary btn" 
                     onclick="window.location.href='{{route('index')}}'">
                        <i class="fas fa-eye"></i>View Invoices&nbsp;
                    </label>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md" style="display:flex;align-items:center;">
                    <label for="itemName" class="mr-2 col-form-label">
                        Invoice Name&nbsp;
                    </label>
                    <input type="text" class="form-control form-control-sm col-sm-3" autocomplete="off" name="invoiceName"  placeholder="Invoice Name" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md mr-5">
                    <label for="itemName" class="mr-2 col-form-label-sm">
                        Item Name&nbsp;
                    </label>
                </div>
                <div class="form-group col-md mr-5">
                    <label for="noOfItem" class="mr-2 col-form-label-sm">
                        # of Items&nbsp;
                    </label>
                </div>
                <div class="form-group col-md mr-5">
                    <label for="Price" class="mr-2 col-form-label-sm">
                        Price&nbsp;
                    </label>
                </div>
                <div class="form-group col-md mr-5">
                    <label for="" class="mr-2 col-form-label-sm">
                        Total&nbsp;
                    </label>
                </div>
                <div class="form-group col-md mr-5">
                    
                </div>
            </div>
            <div class="form-row cloneMe" id="cloneMe">
                <div class="form-group col-md mr-5">
                    <input type="text" class="form-control form-control-sm" autocomplete="off" name="itemName[]"  placeholder="Item Name" required>
                </div>
                <div class="form-group col-md mr-5">
                    <input type="number" class="form-control form-control-sm noOfItem" autocomplete="off" name="noOfItems[]"  placeholder="# of Items" required
                    min=0>
                </div>
                <div class="form-group col-md mr-5">
                    <input type="number" class="form-control form-control-sm price" autocomplete="off" name="price[]" placeholder="Price" required 
                    step=0.01 min=0>
                </div>
                <div class="form-group col-md mr-5">
                    <input type="number" class="form-control form-control-sm total" autocomplete="off" name="total[]" placeholder="Total" required readonly 
                    style="background:white;" step=0.01>
                </div>
                <div class="form-group col-md mr-5">
                    <button class="btn btn-danger pr-1 pl-1 pt-0 pb-0" title="Remove"
                    onclick="sub(this)" type="button">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </div>
            </div>
            <div class="form-row cloneMe" id="cloneMe">
                <div class="form-group col-md mr-5">
                    <input type="text" class="form-control form-control-sm" autocomplete="off" name="itemName[]"  placeholder="Item Name" required>
                </div>
                <div class="form-group col-md mr-5">
                    <input type="number" class="form-control form-control-sm noOfItem" autocomplete="off" name="noOfItems[]"  placeholder="# of Items" required
                    min=0>
                </div>
                <div class="form-group col-md mr-5">
                    <input type="number" class="form-control form-control-sm price" autocomplete="off" name="price[]" placeholder="Price" required 
                    step=0.01 min=0>
                </div>
                <div class="form-group col-md mr-5">
                    <input type="number" class="form-control form-control-sm total" autocomplete="off" name="total[]" placeholder="Total" required readonly style="background:white;" step=0.01>
                </div>
                <div class="form-group col-md mr-5">
                    <button class="btn btn-danger pr-1 pl-1 pt-0 pb-0" title="Remove"
                    onclick="sub(this)" type="button">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </div>
            </div>
            <div class="form-row" id="cloneAbove">
                <div class="form-group col-lg-12">
                   <button type="button" class="btn btn-primary btn-sm" id="addItem">
                        <i class="fas fa-plus"></i>Add Item(<spam id="countItem"></spam>)
                   </button>
                </div>
            </div>
            <div class="form-row mt-1">
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md text-right">
                     <label for="itemName" class="mr-2 col-form-label-sm">
                        Sub Total&nbsp;
                    </label>
                </div>
                <div class="form-group col-md">
                    <input type="number" class="form-control form-control-sm"  
                    name="subTotal" id="subTotal" required readonly 
                    style="background:white;" step=0.01> 
                </div>
                <div class="form-group col-md">
                    
                </div>
            </div>
             <div class="form-row mt">
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md text-right">
                     <label for="itemName" class="mr-2 col-form-label-sm">
                        Tax(%)&nbsp;
                    </label>
                </div>
                <div class="form-group col-md">
                    <input type="number" class="form-control form-control-sm"  
                    name="tax" id="tax" required min=0 step=0.01> 
                </div>
                <div class="form-group col-md">
                    
                </div>
            </div>
            <div class="form-row mt">
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md">
                   
                </div>
                <div class="form-group col-md text-right">
                     <label for="itemName" class="mr-2 col-form-label-sm">
                        Grand Total&nbsp;
                    </label>
                </div>
                <div class="form-group col-md">
                    <input type="number" class="form-control form-control-sm"  
                    name="gTotal" id="gTotal" required readonly style="background:white;"
                    step=0.01> 
                </div>
                <div class="form-group col-md">
                    
                </div>
            </div>
             <div class="form-row" id="cloneAbove">
                <div class="form-group col-lg-12">
                   <button class="btn btn-success btn-sm" type="submit">
                      <i class="fas fa-check-circle"></i>Create
                   </button>
                    <button class="btn btn-light btn-sm" type="reset">
                      <i class="fas fa-redo-alt"></i>Reset
                   </button>
                </div>
            </div>
        </form>
    </div>
    </body>
</html>